/**
 *     Copyright (C) 2019-2023 Ubiqube.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dns-api.proto

package com.ubiqube.etsi.mano.dns.api.v1;

public interface AddHostResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ubiqube.etsi.mano.dns.api.AddHostResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string hostName = 2;</code>
   * @return The hostName.
   */
  java.lang.String getHostName();
  /**
   * <code>string hostName = 2;</code>
   * @return The bytes for hostName.
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>int32 ttl = 3;</code>
   * @return The ttl.
   */
  int getTtl();

  /**
   * <code>string in = 4;</code>
   * @return The in.
   */
  java.lang.String getIn();
  /**
   * <code>string in = 4;</code>
   * @return The bytes for in.
   */
  com.google.protobuf.ByteString
      getInBytes();

  /**
   * <code>string recordType = 5;</code>
   * @return The recordType.
   */
  java.lang.String getRecordType();
  /**
   * <code>string recordType = 5;</code>
   * @return The bytes for recordType.
   */
  com.google.protobuf.ByteString
      getRecordTypeBytes();

  /**
   * <code>string value = 6;</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 6;</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
