/**
 *     Copyright (C) 2019-2023 Ubiqube.
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dns-api.proto

package com.ubiqube.etsi.mano.dns.api.v1;

public interface ListHostsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ubiqube.etsi.mano.dns.api.ListHostsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  java.util.List<com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse> 
      getHostsList();
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  com.ubiqube.etsi.mano.dns.api.v1.AddHostResponse getHosts(int index);
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  int getHostsCount();
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  java.util.List<? extends com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder> 
      getHostsOrBuilderList();
  /**
   * <code>repeated .com.ubiqube.etsi.mano.dns.api.AddHostResponse hosts = 1;</code>
   */
  com.ubiqube.etsi.mano.dns.api.v1.AddHostResponseOrBuilder getHostsOrBuilder(
      int index);
}
