debug: true
keycloak:
  realm: mano-realm
  auth-server-url: http://mano-auth:8110/auth
  ssl-required: external
  resource: mano-nfvo
  credentials:
    secret: 99373315-d8d2-495d-a45d-73aa8cfcd580
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    com:
      ubiqube:
        etsi: DEBUG
    org:
      apache:
        http:
          wire: INFO
        activemq:
          audit: WARN
      elasticsearch:
        client:
          sniff:
            Sniffer: OFF
      hibernate:
        SQL: INFO
      keycloak: INFO
      openstack4j: INFO
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: INFO
        context: INFO
        http: INFO
        jms: INFO
        security: INFO
        web:
          filter: INFO
          servlet: INFO
          reactive: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

mano:
  config:
    type: etsi-mano
  election:
    script-path: /tmp/etsi-mano/election/groovy
  frontend-url: http://localhost:8080/ubi-etsi-mano/sol003
  repository:
    phys-root: /tmp/etsi-mano/repository
  swagger-o-auth2: http://mano-auth:8110/auth/realms/mano-realm/protocol/openid-connect/token

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    contextPath: /ubi-etsi-mano

spring:
  application:
    name: etsi-mano
  artemis:
    mode: embedded
  data:
    rest:
      base-path: /api
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/etsi-mano.h2;AUTO_SERVER=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS mec_meo
    username: sa
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 600000
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    default-property-inclusion: NON_NULL
    generator:
      ignore-unknown: false
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent-output: true
      write-empty-json-arrays: false
  jmx:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
        search:
          backend:
            directory:
              root: /tmp/etsi-mano/indexes
            type: lucene
  liquibase:
    enabled: false
  mvc:
    log-request-details: true
  output:
    ansi:
      enabled: always
  quartz:
    jdbc:
      commentPrefix: '" - "'
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 5000
            isClustered: true
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 10
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://mano-auth:8080/auth/realms/mano-realm
          jwk-set-uri: http://mano-auth:8110/auth/realms/mano-realm/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

springdoc:
  enable-data-rest: false

